services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ${PORT}:${PORT}
    environment:
      NODE_ENV: development
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run start:dev
    depends_on:
      - db
      - redis
  db:
    image: postgres:latest
    container_name: postgres_db
    ports:
      - ${DB_PORT}:${DB_PORT}
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}

    env_file:
      - .env
    volumes:
      - postgres:/var/lib/postgresql/data
  redis:
    image: redis:latest
    ports:
      - '6379:6379'
volumes:
  postgres:
